SET NOCOUNT ON;

IF DB_ID(N'DMPACESSO') IS NOT NULL
BEGIN
  ALTER DATABASE [DMPACESSO] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
  DROP DATABASE [DMPACESSO];
END;
GO

CREATE DATABASE [DMPACESSO];
GO

ALTER DATABASE [DMPACESSO] SET RECOVERY SIMPLE;
GO

USE [DMPACESSO];
GO

CREATE TABLE dbo.__base_info (
  id INT IDENTITY(1,1) PRIMARY KEY,
  reset_em DATETIME2 NOT NULL CONSTRAINT DF___base_info_reset_em DEFAULT SYSUTCDATETIME(),
  reset_por NVARCHAR(128) NOT NULL CONSTRAINT DF___base_info_reset_por DEFAULT SUSER_SNAME(),
  observacao NVARCHAR(300) NULL
);
GO

INSERT INTO dbo.__base_info (observacao)
VALUES (N'Base DMPACESSO recriada para ajuste de acesso');
GO
